version: 2.1

executors:
  test:
    docker:
      - image: circleci/elixir:1.10.4
        environment:
          MIX_ENV: test

jobs:
  test:
    executor: test
    steps:
      - checkout
      - run:
          name: install prerequisites and dependencies
          command: |
            mix local.hex --force
            mix local.rebar --force
            mix deps.get
      - run:
          name: run unit tests
          command: mix test

workflows:
  version: 2
  test:
    jobs:
      - test
