defmodule Smartsheet.Sheet do
  @derive [Jason.Encoder]

  defstruct [
    :id,
    :from_id,
    :owner_id,
    :access_level,
    :attachments,
    :columns,
    :created_at,
    :cross_sheet_references,
    :dependencies_enabled,
    :discussions,
    :effective_attachment_options,
    :favorite,
    :gantt_enabled,
    :has_summary_fields,
    :modified_at,
    :name,
    :owner,
    :permalink,
    :project_settings,
    :read_only,
    :resource_management_enabled,
    :rows,
    :show_parent_rows_for_filters,
    :source,
    :summary,
    :total_row_count,
    :user_permissions,
    :user_settings,
    :version,
    :workspace
  ]

  @type t :: %__MODULE__{
          id: any,
          from_id: any,
          owner_id: any,
          access_level: any,
          attachments: any,
          columns: any,
          created_at: any,
          cross_sheet_references: any,
          dependencies_enabled: any,
          discussions: any,
          effective_attachment_options: any,
          favorite: any,
          gantt_enabled: any,
          has_summary_fields: any,
          modified_at: any,
          name: any,
          owner: any,
          permalink: any,
          project_settings: any,
          read_only: any,
          resource_management_enabled: any,
          rows: any,
          show_parent_rows_for_filters: any,
          source: any,
          summary: any,
          total_row_count: any,
          user_permissions: any,
          user_settings: any,
          version: any,
          workspace: any
        }
end
